const axios = require('axios');

module.exports = {
    name: "country",
    alias: ["nchi", "globe"],
    description: "Get detailed information about any country.",
    category: "location",

    execute: async (sock, chatId, message, args) => {
        // 1. Check if the user provided a country name
        if (!args[0]) {
            return sock.sendMessage(chatId, { 
                text: "🌍 *Usage:* `.country [Country Name]`\nExample: `.country Japan`" 
            });
        }

        const countryName = args.join(" ").trim();
        const url = `https://restcountries.com/v3.1/name/${encodeURIComponent(countryName)}`;

        try {
            // 2. Fetch data from the API
            const response = await axios.get(url);
            const data = response.data[0];

            // 3. Format the information nicely
            const countryInfo = `
🌍 *YASEEN GLOBE INFO* 🌍

✨━━━━━━━━━━━━━━✨
*Country:* ${data.name.common} (${data.cca3})
*Capital:* ${data.capital ? data.capital[0] : 'N/A'}
*Region:* ${data.region}
✨━━━━━━━━━━━━━━✨

📞 *Phone:* ${data.idd.root}${data.idd.suffixes ? data.idd.suffixes[0] : ''}
👥 *Population:* ${data.population.toLocaleString()}
💸 *Currency:* ${Object.values(data.currencies)[0].name}
🌐 *Internet TLD:* ${data.tld ? data.tld[0] : 'N/A'}
⏰ *Timezone:* ${data.timezones[0]}
🇺🇳 *UN Member:* ${data.unMember ? '✅ Yes' : '❌ No'}
🚗 *Driving:* ${data.car.side.toUpperCase()}

*Generated by YAS-TECH*
            `.trim();

            // 4. Send the result with the country flag as an image
            const flagUrl = data.flags.png;

            return sock.sendMessage(chatId, { 
                image: { url: flagUrl }, 
                caption: countryInfo 
            }, { quoted: message });

        } catch (err) {
            console.error("Country Info Error:", err.message);
            return sock.sendMessage(chatId, { 
                text: "❌ *Error:* Country not found. Please check your spelling." 
            });
        }
    }
};
