const hadiths = [
  { n: "Umar bin Al-Khattab", e: "Actions are but by intentions and every man shall have only which he intended.", s: "Hakika vitendo huzingatiwa kwa nia, na kila mtu atapata kile alichokinuia.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "A Muslim is the one from whose tongue and hands the Muslims are safe.", s: "Muislamu wa kweli ni yule ambaye Waislamu wenzake wamesalimika na ulimi wake na mikono yake.", r: "Sahih Muslim" },
  { n: "Anas bin Malik", e: "None of you truly believes until he loves for his brother what he loves for himself.", s: "Hajakamilisha imani mmoja wenu mpaka ampendelee ndugu yake kile anachojipendelea nafsi yake.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "The strong man is not one who can wrestle, but the strong man is one who controls himself in anger.", s: "Mwenye nguvu si yule anayeweza kushindana, bali mwenye nguvu ni yule anayejimiliki wakati wa hasira.", r: "Sahih Bukhari" },
  { n: "Ibn Abbas", e: "Be mindful of Allah and He will protect you. Be mindful of Allah and you will find Him before you.", s: "Mhifadhi Allah naye atakuhifadhi. Mhifadhi Allah nawe utamkuta mbele yako.", r: "Tirmidhi" },
  { n: "Abu Hurairah", e: "Allah does not look at your figures or your attire but He looks at your hearts and accomplishments.", s: "Allah haangalii sura zenu wala mavazi yenu, bali anaangalia nyoyo zenu na vitendo vyenu.", r: "Sahih Muslim" },
  { n: "Abdullah bin Amr", e: "The best of you are those who are best to their women.", s: "Mbora wenu ni yule aliye mbora kwa wanawake wake.", r: "Tirmidhi" },
  { n: "Abu Shurayh", e: "He who believes in Allah and the Last Day should honor his guest.", s: "Anayemwamini Allah na Siku ya Mwisho, basi amkirimu mgeni wake.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "Wealth is not in having many possessions, but wealth is the richness of the soul.", s: "Utajiri si kuwa na mali nyingi, bali utajiri ni kutosheka kwa nafsi.", r: "Sahih Bukhari" },
  { n: "Aisha (RA)", e: "The most beloved of deeds to Allah are those that are most consistent, even if they are small.", s: "Vitendo vinavyopendwa zaidi na Allah ni vile ambavyo ni vya kudumu, hata kama ni vidogo.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "The upper hand is better than the lower hand (the one that gives).", s: "Mkono wa juu ni bora kuliko mkono wa chini (anayetoa ni bora).", r: "Sahih Bukhari" },
  { n: "Jabir bin Abdullah", e: "Every good deed is a form of charity.", s: "Kila kitendo chema ni sadaka.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "Avoid suspicion, for suspicion is the worst of false tales.", s: "Epuqeni dhana, kwani dhana ni mazungumzo ya uongo zaidi.", r: "Sahih Bukhari" },
  { n: "Ibn Umar", e: "Be in this world as if you were a stranger or a traveler.", s: "Ishi duniani kama vile wewe ni mgeni au mpita njia.", r: "Sahih Bukhari" },
  { n: "Mu’adh bin Jabal", e: "Fear Allah wherever you are and follow up a bad deed with a good one.", s: "Mche Allah popote ulipo, na fuatisha kitendo kibaya kwa kile chema.", r: "Tirmidhi" },
  { n: "Abu Hurairah", e: "The world is a prison for the believer and a paradise for the disbeliever.", s: "Dunia ni gereza kwa muumini na ni pepo kwa kafiri.", r: "Sahih Muslim" },
  { n: "Aisha (RA)", e: "Allah is Kind and He loves kindness in all matters.", s: "Allah ni Mpole na anapenda upole katika mambo yote.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "A good word is a form of charity.", s: "Neno jema ni sadaka.", r: "Sahih Bukhari" },
  { n: "Ibn Mas'ud", e: "The most beloved of deeds to Allah is prayer at its proper time.", s: "Kitendo kinachopendwa zaidi na Allah ni swala katika wakati wake.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "He who does not thank people does not thank Allah.", s: "Asiyewashukuru watu, hamshukuru Allah.", r: "Tirmidhi" },
  { n: "Anas bin Malik", e: "Make things easy and do not make them difficult.", s: "Fanyeni mambo yawe mepesi na wala msifanye yawe magumu.", r: "Sahih Bukhari" },
  { n: "Abu Hurairah", e: "Part of a person’s being a good Muslim is leaving alone that which does not concern him.", s: "Sehemu ya uzuri wa Uislamu wa mtu ni kuacha yasiyomuhusu.", r: "Tirmidhi" },
  { n: "Ibn Abbas", e: "Take advantage of five before five: your youth before your old age...", s: "Tumia fursa tano kabla ya tano: ujana wako kabla ya uzee wako...", r: "Al-Hakim" },
  { n: "Abu Hurairah", e: "The most perfect of believers in faith are those with the best character.", s: "Muumini aliyekamilika zaidi katika imani ni yule mwenye tabia njema zaidi.", r: "Tirmidhi" },
  { n: "Aisha (RA)", e: "The best of you are those who are best to their families.", s: "Mbora wenu ni yule aliye mbora kwa familia yake.", r: "Tirmidhi" },
  { n: "Abu Bakr", e: "Truthfulness is a trust and lying is a betrayal.", s: "Ukweli ni amana na uongo ni usaliti.", r: "Al-Bidayah" },
  { n: "Abu Hurairah", e: "Look at those who are beneath you and do not look at those who are above you.", s: "Waangalie walio chini yako na wala usiwaangalie walio juu yako.", r: "Sahih Muslim" },
  { n: "Ibn Umar", e: "The most beloved of people to Allah is the one who brings most benefit to people.", s: "Mtu anayependwa zaidi na Allah ni yule anayewanufaisha zaidi watu.", r: "Al-Mu’jam" },
  { n: "Abu Hurairah", e: "Seven people Allah will shade in His shade on the Day when there is no shade except His shade.", s: "Watu saba Allah atawatia katika kivuli chake Siku ambayo hakuna kivuli isipokuwa chake.", r: "Sahih Bukhari" },
  { n: "Anas bin Malik", e: "The believer is simple and noble, while the wicked person is deceitful and ignoble.", s: "Muumini ni mwepesi na mkarimu, wakati mtu muovu ni mdanganyifu na dhalili.", r: "Tirmidhi" }
];

module.exports = hadiths;
