module.exports = {
    name: "listgroups",
    alias: ["groups", "lg", "magroup"],
    description: "List all groups the bot is currently in.",
    category: "group",

    execute: async (sock, chatId, message, args) => {
        try {
            await sock.sendMessage(chatId, { react: { text: '📂', key: message.key } });

            // Fetching all groups the bot is a member of
            const getGroups = await sock.groupFetchAllParticipating();
            const groups = Object.entries(getGroups).slice(0).map(entry => entry[1]);

            if (groups.length === 0) {
                return sock.sendMessage(chatId, { text: "❌ *YAS-TECH:* I am not in any groups at the moment." });
            }

            let responseText = `📂 *YASEEN-ＭＤ ＧＲＯＵＰ ＬＩＳＴ*\n`;
            responseText += `━━━━━━━━━━━━━━━━━━━━\n`;
            responseText += `Total Groups: *${groups.length}*\n\n`;

            groups.forEach((group, i) => {
                responseText += `*${i + 1}.* ${group.subject}\n`;
                responseText += `   ID: \`${group.id}\`\n`;
                responseText += `   Members: ${group.participants.length}\n\n`;
            });

            responseText += `*Generated by YAS-TECH Intelligence* 🕹️`;

            return await sock.sendMessage(chatId, { text: responseText }, { quoted: message });

        } catch (err) {
            console.error("List Groups Error:", err);
            return sock.sendMessage(chatId, { text: "❌ *ERROR:* Failed to retrieve the group list." });
        }
    }
};
