const axios = require('axios');

// Initialize Global Cache if not exists
if (!global.tiktokSearchCache) global.tiktokSearchCache = {};

module.exports = {
    name: "tiktok",
    alias: ["tt", "ttdl", "ttsearch", "more", "ttimage", "ttmp4"],
    description: "Search Menu, Selection, Replies, and Prexzy Text-to-Media.",
    category: "downloader",

    execute: async (sock, chatId, message, args) => {
        const from = chatId;
        const msg = message.message;
        const body = msg?.conversation || msg?.extendedTextMessage?.text || "";
        const command = body.split(' ')[0].toLowerCase().slice(1);
        const query = args.join(" ").trim();
        const prefix = ".";

        // --- 🟢 1. YAS-TECH OFFICIAL MANUAL ---
        if (!query && command !== "more" && !msg?.extendedTextMessage?.contextInfo?.quotedMessage) {
            const manual = `✦═══════════════════════◆
🎵  *YASEEN  ＴＩＫＴＯＫ  ＮＯＤＥ*
✦═══════════════════════◆

🛰️  *ＯＰＥＲＡＴＩＯＮＡＬ  ＣＯＭＭＡＮＤＳ:*
> *${prefix}tiktok [keyword]* ➔ Search Menu
> *${prefix}tiktok [link]* ➔ Direct Download
> *${prefix}tiktok [number]* ➔ Download from List
> *${prefix}more* ➔ Next 10 Results

🎨  *ＣＲＥＡＴＩＶＥ  ＴＯＯＬＳ:*
> *${prefix}ttimage [text]* ➔ Text to Image
> *${prefix}ttmp4 [text]* ➔ Text to MP4

💡  *ＴＩＰ:* Reply to a search list with a number to download!

✦═══════════════════════◆
_© 2026 YAS-TECH • Media Node_`;
            return await sock.sendMessage(from, { 
                image: { url: "https://files.catbox.moe/yb43pn.jpg" }, 
                caption: manual 
            }, { quoted: message });
        }

        // --- 🔄 2. THE .MORE FIX (Pagination) ---
        if (command === "more" || (command === "tiktok" && query.toLowerCase() === "more")) {
            if (!global.tiktokSearchCache[from] || !global.tiktokSearchCache[from].results) {
                return await sock.sendMessage(from, { text: "❌ *CACHE ERROR:* No active search found. Start a new search first." });
            }
            
            // Advance the page
            global.tiktokSearchCache[from].page += 1;
            return await sendTikTokMenu(sock, from, message);
        }

        // --- 🎨 3. PREXZY CREATIVE TOOLS ---
        if (command === "ttimage" || command === "ttmp4") {
            if (!query) return sock.sendMessage(from, { text: `🔍 *Usage:* ${prefix}${command} [text]` });
            await sock.sendMessage(from, { react: { text: '✨', key: message.key } });
            const endpoint = command === "ttimage" ? "texttoimage" : "texttomultimp4";
            const genUrl = `https://apis.prexzyvilla.site/imagecreator/${endpoint}?text=${encodeURIComponent(query)}`;
            return await sock.sendMessage(from, { 
                [command === "ttimage" ? "image" : "video"]: { url: genUrl }, 
                caption: `✨ *Generated by YAS-TECH*` 
            }, { quoted: message });
        }

        // --- 🔢 4. PROCESS SELECTION (Reply or Number) ---
        const quotedMsg = msg?.extendedTextMessage?.contextInfo?.quotedMessage;
        const quotedText = quotedMsg?.conversation || quotedMsg?.extendedTextMessage?.text || "";
        
        let selectionIndex = null;
        if (quotedText.includes("ＴＩＫＴＯＫ  ＲＥＳＵＬＴＳ") && !isNaN(body.trim())) {
            selectionIndex = parseInt(body.trim()) - 1;
        } else if (!isNaN(query) && global.tiktokSearchCache[from]) {
            selectionIndex = parseInt(query) - 1;
        }

        if (selectionIndex !== null && global.tiktokSearchCache[from]) {
            const results = global.tiktokSearchCache[from].results;
            if (results && results[selectionIndex]) {
                await sock.sendMessage(from, { react: { text: '⏳', key: message.key } });
                const vid = results[selectionIndex];
                let cap = `✅ *ＴＩＫＴＯＫ  ＥＸＴＲＡＣＴＥＤ*\n\n> 📍 *Title:* ${vid.title}\n\n*🛡️ YASEEN－ＭＤ 🛡️*`;
                return await sock.sendMessage(from, { video: { url: vid.play }, caption: cap }, { quoted: message });
            }
        }

        // --- 📥 5. DIRECT LINK DOWNLOAD ---
        if (query.match(/tiktok\.com/gi)) {
            await sock.sendMessage(from, { react: { text: '⏳', key: message.key } });
            try {
                const res = await axios.get(`https://www.tikwm.com/api/?url=${encodeURIComponent(query)}`);
                const vid = res.data.data;
                let cap = `✅ *ＤＯＷＮＬＯＡＤ*\n\n> 📍 *Title:* ${vid.title || "Success"}\n\n*🛡️ YASEEN－ＭＤ 🛡️*`;
                return await sock.sendMessage(from, { video: { url: vid.play }, caption: cap }, { quoted: message });
            } catch (e) { return sock.sendMessage(from, { text: "❌ Link bypass failed." }); }
        }

        // --- 🔍 6. NEW KEYWORD SEARCH ---
        if (query && isNaN(query)) {
            try {
                await sock.sendMessage(from, { react: { text: '🔍', key: message.key } });
                const { data } = await axios.get(`https://apis.prexzyvilla.site/search/tiktoksearch?q=${encodeURIComponent(query)}`);
                if (!data.status || !data.data.length) throw new Error();

                // Save fresh results to cache
                global.tiktokSearchCache[from] = { 
                    results: data.data, 
                    page: 0, 
                    query: query 
                };
                return await sendTikTokMenu(sock, from, message);
            } catch (e) { return sock.sendMessage(from, { text: "❌ No results found." }); }
        }
    }
};

// 📜 Helper: Generate the 10-item menu
async function sendTikTokMenu(sock, from, message) {
    const cache = global.tiktokSearchCache[from];
    const start = cache.page * 10;
    const items = cache.results.slice(start, start + 10);

    if (items.length === 0) {
        cache.page = 0; // Reset to page 1 if they run out
        return await sock.sendMessage(from, { text: "🏁 *End of results.* Reverting to Page 1." });
    }

    let menu = `🎵 *ＴＩＫＴＯＫ  ＲＥＳＵＬＴＳ  (P. ${cache.page + 1})*\n\n`;
    menu += `Query: _${cache.query}_\n\n`;
    
    items.forEach((v, i) => {
        menu += `*${start + i + 1}.* ${v.title.substring(0, 45)}...\n   └ ⏱️ *Duration:* ${v.duration}s\n\n`;
    });

    menu += `💡 *Reply with the number to download.*\n💡 *Type .more for next page.*`;
    return await sock.sendMessage(from, { text: menu }, { quoted: message });
}
