const axios = require('axios');

module.exports = {
    name: "wth",
    alias: ["weather", "halihewa"],
    description: "Fetches real-time global weather data using OpenWeatherMap API.",
    category: "location",

    execute: async (sock, chatId, message, args) => {
        // 1. Validate if the user provided a location
        if (!args[0]) {
            return sock.sendMessage(chatId, { 
                text: "🌍 *Usage:* `.wth [City Name]`\nExample: `.wth Arusha`" 
            });
        }

        // 2. Clean and join the location arguments
        const location = args.join(" ").trim();
        
        // 3. Your verified API Key from the screenshot
        const apiKey = "c7b1572fe5fd8598afbda70458fd89c8"; 
        const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=metric&appid=${apiKey}`;

        try {
            // 4. Request data from the API
            const response = await axios.get(url);
            const data = response.data;

            // 5. Construct the formatted weather report
            const weatherReport = `
🌍 *WEATHER REPORT: ${data.name}, ${data.sys.country}* 🌍

🌡️ *Temperature:* ${data.main.temp}°C
☁️ *Condition:* ${data.weather[0].description}
💧 *Humidity:* ${data.main.humidity}%
💨 *Wind Speed:* ${data.wind.speed} m/s
🌅 *Sunrise:* ${new Date(data.sys.sunrise * 1000).toLocaleTimeString()}
🌇 *Sunset:* ${new Date(data.sys.sunset * 1000).toLocaleTimeString()}

*Generated by YAS-TECH | Arusha Division*
            `.trim();

            // 6. Send the successful response
            return sock.sendMessage(chatId, { text: weatherReport });

        } catch (err) {
            // 7. Error handling for invalid cities or API downtime
            console.error("Weather API Error:", err.message);
            return sock.sendMessage(chatId, { 
                text: "❌ *Error:* City not found. Please ensure the spelling is correct and try again later." 
            });
        }
    }
};
